//go:build linux

package linuxfs

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/biendo27/linux-deep-clean/internal/domain"
	"github.com/biendo27/linux-deep-clean/internal/mounts"
	"golang.org/x/sys/unix"
)

const (
	privateLedgerNamespacePrefix    = "ldc-ledger-"
	privateLedgerLockBasename       = "ldc-ledger-v1.lock"
	privateLedgerRecordPrefix       = "ldc-ledger-v1-"
	privateLedgerRecordSuffix       = ".cbor"
	privateLedgerLockContents       = "ldc-ledger-v1-lock\n"
	privateLedgerDigestHexBytes     = 64
	privateLedgerTokenHexBytes      = 64
	maximumPrivateLedgerOrdinal     = uint8(15)
	maximumPrivateLedgerRecords     = 256
	maximumPrivateLedgerDirEntries  = maximumPrivateLedgerRecords + 16
	privateLedgerDirectoryReadBytes = 32 << 10
	privateLedgerLockRetryDelay     = time.Millisecond
)

const privateLedgerEntryMask = publishedFileIdentityMask |
	domain.FilesystemFieldSize |
	domain.FilesystemFieldModifiedAt |
	domain.FilesystemFieldChangedAt

// PrivateLedgerRecordID identifies one immutable v1 ledger frame. Its file
// name is deliberately derived only inside linuxfs; callers can correlate a
// record with its action binding, opaque reservation token, and transition
// ordinal without gaining path or descriptor authority. This is a state-owned
// internal port: architecture tests prohibit every other production package
// from constructing or using ledger record identities.
type PrivateLedgerRecordID struct {
	actionBindingDigest string
	token               string
	ordinal             uint8
}

// NewPrivateLedgerRecordID validates the canonical components of an immutable
// ledger record identity. The token must be generated by the state ledger; a
// constructor is exposed only so replay can rebuild a validated opaque ID from
// retained record facts.
func NewPrivateLedgerRecordID(actionBindingDigest, token string, ordinal uint8) (PrivateLedgerRecordID, error) {
	if len(actionBindingDigest) != privateLedgerDigestHexBytes || !isLowerHex(actionBindingDigest) {
		return PrivateLedgerRecordID{}, fmt.Errorf("%w: action binding digest must be %d lowercase hexadecimal bytes", ErrUnsupported, privateLedgerDigestHexBytes)
	}
	if !strings.HasPrefix(token, "ldc-") || len(token) != len("ldc-")+privateLedgerTokenHexBytes || !isLowerHex(token[len("ldc-"):]) {
		return PrivateLedgerRecordID{}, fmt.Errorf("%w: ledger token must be ldc- plus %d lowercase hexadecimal bytes", ErrUnsupported, privateLedgerTokenHexBytes)
	}
	if ordinal > maximumPrivateLedgerOrdinal {
		return PrivateLedgerRecordID{}, fmt.Errorf("%w: ledger ordinal %d exceeds %d", ErrUnsupported, ordinal, maximumPrivateLedgerOrdinal)
	}
	return PrivateLedgerRecordID{
		actionBindingDigest: actionBindingDigest,
		token:               token,
		ordinal:             ordinal,
	}, nil
}

// ActionBindingDigest returns the canonical digest text used to derive this
// record identity. It is a value, not an authority grant.
func (id PrivateLedgerRecordID) ActionBindingDigest() string { return id.actionBindingDigest }

// Token returns the opaque reservation token associated with this record.
func (id PrivateLedgerRecordID) Token() string { return id.token }

// Ordinal returns the immutable transition position associated with this
// record identity.
func (id PrivateLedgerRecordID) Ordinal() uint8 { return id.ordinal }

func (id PrivateLedgerRecordID) basename() string {
	return fmt.Sprintf("%s%s-%s-%02d%s", privateLedgerRecordPrefix, id.actionBindingDigest, id.token, id.ordinal, privateLedgerRecordSuffix)
}

func (id PrivateLedgerRecordID) validate() error {
	_, err := NewPrivateLedgerRecordID(id.actionBindingDigest, id.token, id.ordinal)
	return err
}

func isLowerHex(value string) bool {
	for _, character := range []byte(value) {
		if (character < '0' || character > '9') && (character < 'a' || character > 'f') {
			return false
		}
	}
	return true
}

// PrivateLedgerSession is an opaque descriptor-scoped critical section. It is
// active only while a WithPrivateLedger*Session callback is executing, holds a
// verified kernel lock for that whole callback, and never exposes a pathname
// or raw descriptor to the state package.
type PrivateLedgerSession struct {
	mu sync.Mutex

	directory   *PrivateDirectoryLease
	directoryFD int
	lockID      domain.FilesystemSnapshot
	writable    bool
	active      bool
}

// WithPrivateLedgerWriteSession enters the only session that can initialize a
// private ledger or durably publish a record. The callback holds an OS lock
// across its lookup, conflict check, and publication sequence. The raw session
// port is reserved to internal/state by the architecture boundary.
func WithPrivateLedgerWriteSession(ctx context.Context, directory *PrivateDirectoryLease, callback func(*PrivateLedgerSession) error) error {
	return withPrivateLedgerSession(ctx, directory, true, callback)
}

// WithPrivateLedgerReadSession enters a verified shared lock without creating
// any on-disk entry. A missing static lock is distinguishable from an existing
// empty ledger so callers never treat an uninitialized state directory as a
// durable ledger.
func WithPrivateLedgerReadSession(ctx context.Context, directory *PrivateDirectoryLease, callback func(*PrivateLedgerSession) error) error {
	return withPrivateLedgerSession(ctx, directory, false, callback)
}

func withPrivateLedgerSession(ctx context.Context, directory *PrivateDirectoryLease, writable bool, callback func(*PrivateLedgerSession) error) error {
	if err := contextError(ctx); err != nil {
		return err
	}
	if directory == nil || callback == nil {
		return fmt.Errorf("%w: qualified private-state ledger callback is required", ErrUnsupported)
	}
	if directory.Kind() != mounts.LayoutPrivateState {
		return fmt.Errorf("%w: private ledger requires %q, got %q", ErrUnsupported, mounts.LayoutPrivateState, directory.Kind())
	}

	return directory.withFD(func(directoryFD int) (result error) {
		session, release, err := startPrivateLedgerSession(ctx, directory, directoryFD, writable)
		if err != nil {
			return err
		}
		defer func() {
			session.deactivate()
			releaseErr := release()
			if recovered := recover(); recovered != nil {
				panic(recovered)
			}
			if result == nil {
				result = releaseErr
			}
		}()
		return callback(session)
	})
}

func startPrivateLedgerSession(ctx context.Context, directory *PrivateDirectoryLease, directoryFD int, writable bool) (*PrivateLedgerSession, func() error, error) {
	if writable {
		if err := preflightPrivateLedgerInitialization(ctx, directoryFD); err != nil {
			return nil, nil, err
		}
	}
	lockFD, lockID, _, initialized, err := openPrivateLedgerLock(directoryFD, writable)
	if err != nil {
		if !writable && errors.Is(err, unix.ENOENT) {
			return nil, nil, classifyMissingReadOnlyLedger(ctx, directoryFD)
		}
		return nil, nil, err
	}
	locked := false
	handedOff := false
	defer func() {
		if handedOff {
			return
		}
		if locked {
			_ = unix.Flock(lockFD, unix.LOCK_UN)
		}
		_ = unix.Close(lockFD)
	}()

	lockMode := unix.LOCK_SH
	if writable {
		lockMode = unix.LOCK_EX
	}
	if err := acquirePrivateLedgerLock(ctx, lockFD, lockMode); err != nil {
		return nil, nil, err
	}
	locked = true

	if !initialized {
		if !writable {
			return nil, nil, fmt.Errorf("%w: private ledger lock initialization is incomplete", ErrDrifted)
		}
		records, err := privateLedgerRecordIDsAt(ctx, directoryFD, maximumPrivateLedgerRecords)
		if err != nil {
			return nil, nil, err
		}
		if len(records) != 0 {
			return nil, nil, fmt.Errorf("%w: retained ledger records exist around an uninitialized static lock", ErrDrifted)
		}
		// Finish a newly-created or retained zero-byte static entry only after the
		// lock is held. A cancellation before that point leaves a marker a later
		// writer can safely finish after rechecking that no records exist.
		if err := initializePrivateLedgerLock(lockFD, directoryFD); err != nil {
			return nil, nil, err
		}
		lockID, err = snapshotPrivateLedgerLock(lockFD)
		if err != nil {
			return nil, nil, postCreateIdentityError("initialized private ledger lock", err)
		}
		if err := verifyPrivateLedgerLock(context.Background(), directoryFD, lockID); err != nil {
			return nil, nil, postCreateIdentityError("initialized private ledger lock name", err)
		}
		if err := contextError(ctx); err != nil {
			return nil, nil, err
		}
	} else if err := verifyPrivateLedgerLock(ctx, directoryFD, lockID); err != nil {
		return nil, nil, err
	}

	if _, err := privateLedgerRecordIDsAt(ctx, directoryFD, maximumPrivateLedgerRecords); err != nil {
		return nil, nil, err
	}

	session := &PrivateLedgerSession{
		directory:   directory,
		directoryFD: directoryFD,
		lockID:      lockID,
		writable:    writable,
		active:      true,
	}
	release := func() error {
		session.deactivate()
		unlockErr := unix.Flock(lockFD, unix.LOCK_UN)
		locked = false
		closeErr := unix.Close(lockFD)
		if unlockErr != nil || closeErr != nil {
			return fmt.Errorf("%w: release private ledger lock: %v", ErrInterrupted, errors.Join(unlockErr, closeErr))
		}
		return nil
	}
	handedOff = true
	return session, release, nil
}

func (session *PrivateLedgerSession) deactivate() {
	if session == nil {
		return
	}
	session.mu.Lock()
	defer session.mu.Unlock()
	session.active = false
	session.directoryFD = -1
}

// Publish durably creates one immutable frame under the held write session.
// It never overwrites a retained record. A post-create ambiguity remains an
// ErrInterrupted result so the caller must reload the exact record ID.
func (session *PrivateLedgerSession) Publish(ctx context.Context, id PrivateLedgerRecordID, contents []byte) error {
	if err := id.validate(); err != nil {
		return err
	}
	if len(contents) > maximumDurableFileBytes {
		return fmt.Errorf("%w: private ledger frame exceeds %d-byte limit", ErrUnsupported, maximumDurableFileBytes)
	}
	return session.withActive(ctx, func() error {
		if !session.writable {
			return fmt.Errorf("%w: read-only private ledger session cannot publish", ErrUnsupported)
		}
		records, err := privateLedgerRecordIDsAt(ctx, session.directoryFD, maximumPrivateLedgerRecords)
		if err != nil {
			return err
		}
		if len(records) >= maximumPrivateLedgerRecords {
			return fmt.Errorf("%w: private ledger record capacity %d reached", ErrUnsupported, maximumPrivateLedgerRecords)
		}
		if err := publishFileDurableAtWith(ctx, session.directoryFD, id.basename(), contents, defaultDurableFileHooks()); err != nil {
			return err
		}
		if err := session.recheckLocked(ctx); err != nil {
			return postCreateIdentityError("private ledger after record publication", err)
		}
		return nil
	})
}

// Read returns an exact bounded copy of one immutable record. It reads only a
// LinuxFS-validated filename while the session lock remains held.
func (session *PrivateLedgerSession) Read(ctx context.Context, id PrivateLedgerRecordID, maximumBytes int) ([]byte, error) {
	if err := id.validate(); err != nil {
		return nil, err
	}
	if maximumBytes <= 0 || maximumBytes > maximumDurableFileBytes {
		return nil, fmt.Errorf("%w: private ledger read limit must be between 1 and %d bytes", ErrUnsupported, maximumDurableFileBytes)
	}

	var contents []byte
	err := session.withActive(ctx, func() error {
		var err error
		contents, err = readPrivateLedgerRecord(ctx, session.directoryFD, id, maximumBytes)
		return err
	})
	if err != nil {
		return nil, err
	}
	return contents, nil
}

// List returns a deterministic, fully validated bounded inventory of retained
// record identities. It never truncates an over-limit result or hides a
// malformed ledger-namespaced entry.
func (session *PrivateLedgerSession) List(ctx context.Context, limit int) ([]PrivateLedgerRecordID, error) {
	if limit <= 0 || limit > maximumPrivateLedgerRecords {
		return nil, fmt.Errorf("%w: private ledger list limit must be between 1 and %d", ErrUnsupported, maximumPrivateLedgerRecords)
	}

	var records []PrivateLedgerRecordID
	err := session.withActive(ctx, func() error {
		var err error
		records, err = privateLedgerRecordIDsAt(ctx, session.directoryFD, limit)
		return err
	})
	if err != nil {
		return nil, err
	}
	return records, nil
}

func (session *PrivateLedgerSession) withActive(ctx context.Context, operation func() error) error {
	if err := contextError(ctx); err != nil {
		return err
	}
	if session == nil || operation == nil {
		return fmt.Errorf("%w: active private ledger session is required", ErrUnsupported)
	}
	session.mu.Lock()
	defer session.mu.Unlock()
	if !session.active || session.directory == nil || session.directoryFD < 0 {
		return fmt.Errorf("%w: private ledger session is closed", ErrDrifted)
	}
	if err := session.recheckLocked(ctx); err != nil {
		return err
	}
	if err := operation(); err != nil {
		return err
	}
	return session.recheckLocked(ctx)
}

func (session *PrivateLedgerSession) recheckLocked(ctx context.Context) error {
	if err := contextError(ctx); err != nil {
		return err
	}
	if session.directory == nil || session.directoryFD < 0 {
		return fmt.Errorf("%w: private ledger directory is unavailable", ErrDrifted)
	}
	if err := session.directory.recheckLocked(); err != nil {
		return err
	}
	if err := session.directory.recheckFDLocked(session.directoryFD); err != nil {
		return err
	}
	return verifyPrivateLedgerLock(ctx, session.directoryFD, session.lockID)
}

func openPrivateLedgerLock(directoryFD int, writable bool) (int, domain.FilesystemSnapshot, bool, bool, error) {
	if directoryFD < 0 {
		return -1, domain.FilesystemSnapshot{}, false, false, fmt.Errorf("%w: private-state directory descriptor is required", ErrUnsupported)
	}
	if !writable {
		fd, err := unix.Openat(directoryFD, privateLedgerLockBasename, unix.O_RDONLY|unix.O_NONBLOCK|unix.O_CLOEXEC|unix.O_NOFOLLOW, 0)
		if err != nil {
			if errors.Is(err, unix.ENOENT) {
				return -1, domain.FilesystemSnapshot{}, false, false, err
			}
			return -1, domain.FilesystemSnapshot{}, false, false, classifyPrivateLedgerLockOpen(err)
		}
		identity, initialized, err := snapshotPrivateLedgerLockState(fd)
		if err != nil {
			_ = unix.Close(fd)
			return -1, domain.FilesystemSnapshot{}, false, false, err
		}
		return fd, identity, false, initialized, nil
	}

	fd, err := unix.Openat(directoryFD, privateLedgerLockBasename, unix.O_RDWR|unix.O_CREAT|unix.O_EXCL|unix.O_CLOEXEC|unix.O_NOFOLLOW, durableFileMode)
	if err == nil {
		if err := snapshotPrivateLedgerNewLock(fd); err != nil {
			_ = unix.Close(fd)
			return -1, domain.FilesystemSnapshot{}, false, false, postCreateIdentityError("new private ledger lock", err)
		}
		return fd, domain.FilesystemSnapshot{}, true, false, nil
	}
	if !errors.Is(err, unix.EEXIST) {
		return -1, domain.FilesystemSnapshot{}, false, false, classifyPrivateLedgerLockOpen(err)
	}

	fd, err = unix.Openat(directoryFD, privateLedgerLockBasename, unix.O_RDWR|unix.O_NONBLOCK|unix.O_CLOEXEC|unix.O_NOFOLLOW, 0)
	if err != nil {
		return -1, domain.FilesystemSnapshot{}, false, false, classifyPrivateLedgerLockOpen(err)
	}
	identity, initialized, err := snapshotPrivateLedgerLockState(fd)
	if err != nil {
		_ = unix.Close(fd)
		return -1, domain.FilesystemSnapshot{}, false, false, err
	}
	return fd, identity, false, initialized, nil
}

// preflightPrivateLedgerInitialization refuses to recreate a deleted static
// lock around retained records. It performs no mutation; a second bounded
// inventory check happens under the newly acquired lock before initialization
// to make the normal no-lock case safe against a concurrent hostile writer.
func preflightPrivateLedgerInitialization(ctx context.Context, directoryFD int) error {
	fd, err := unix.Openat(directoryFD, privateLedgerLockBasename, unix.O_RDONLY|unix.O_NONBLOCK|unix.O_CLOEXEC|unix.O_NOFOLLOW, 0)
	if err == nil {
		return unix.Close(fd)
	}
	if !errors.Is(err, unix.ENOENT) {
		return classifyPrivateLedgerLockOpen(err)
	}
	records, err := privateLedgerRecordIDsAt(ctx, directoryFD, maximumPrivateLedgerRecords)
	if err != nil {
		return err
	}
	if len(records) != 0 {
		return fmt.Errorf("%w: retained ledger records exist without a static lock", ErrDrifted)
	}
	return nil
}

func initializePrivateLedgerLock(lockFD, directoryFD int) error {
	if err := writeDurableFileContents(context.Background(), lockFD, []byte(privateLedgerLockContents), unix.Write); err != nil {
		return fmt.Errorf("%w: initialize private ledger lock contents: %v", ErrInterrupted, err)
	}
	if err := unix.Fsync(lockFD); err != nil {
		return classifyPrivateLedgerSync("sync private ledger lock", err)
	}
	if err := unix.Fsync(directoryFD); err != nil {
		return classifyPrivateLedgerSync("sync private ledger lock directory", err)
	}
	return nil
}

func acquirePrivateLedgerLock(ctx context.Context, fd, lockMode int) error {
	for {
		if err := contextError(ctx); err != nil {
			return err
		}
		err := unix.Flock(fd, lockMode|unix.LOCK_NB)
		if err == nil {
			return nil
		}
		if !errors.Is(err, unix.EWOULDBLOCK) && !errors.Is(err, unix.EAGAIN) {
			switch {
			case errors.Is(err, unix.ENOSYS), errors.Is(err, unix.EOPNOTSUPP), errors.Is(err, unix.ENOLCK):
				return fmt.Errorf("%w: private ledger lock is unavailable: %v", ErrUnsupported, err)
			case errors.Is(err, unix.EINTR):
				continue
			default:
				return fmt.Errorf("%w: acquire private ledger lock: %v", ErrDrifted, err)
			}
		}

		timer := time.NewTimer(privateLedgerLockRetryDelay)
		select {
		case <-ctx.Done():
			if !timer.Stop() {
				select {
				case <-timer.C:
				default:
				}
			}
			return contextError(ctx)
		case <-timer.C:
		}
	}
}

func classifyMissingReadOnlyLedger(ctx context.Context, directoryFD int) error {
	records, err := privateLedgerRecordIDsAt(ctx, directoryFD, maximumPrivateLedgerRecords)
	if err != nil {
		return err
	}
	if len(records) != 0 {
		return fmt.Errorf("%w: retained ledger records exist without a static lock", ErrDrifted)
	}
	return ErrLedgerNotInitialized
}

func classifyPrivateLedgerLockOpen(err error) error {
	switch {
	case errors.Is(err, unix.ELOOP), errors.Is(err, unix.ENOTDIR), errors.Is(err, unix.ENOENT):
		return fmt.Errorf("%w: private ledger lock is missing, replaced, or hostile: %v", ErrDrifted, err)
	case errors.Is(err, unix.ENOSYS), errors.Is(err, unix.EOPNOTSUPP), errors.Is(err, unix.EROFS):
		return fmt.Errorf("%w: private ledger lock cannot be opened safely: %v", ErrUnsupported, err)
	case errors.Is(err, unix.EINTR), errors.Is(err, unix.EAGAIN):
		return fmt.Errorf("%w: private ledger lock open did not complete: %v", ErrInterrupted, err)
	default:
		return fmt.Errorf("%w: private ledger lock open failed: %v", ErrDrifted, err)
	}
}

func classifyPrivateLedgerSync(operation string, err error) error {
	switch {
	case errors.Is(err, unix.EBADF), errors.Is(err, unix.EINVAL), errors.Is(err, unix.EOPNOTSUPP), errors.Is(err, unix.EROFS):
		return fmt.Errorf("%w: %s is unavailable: %v", ErrUnsupported, operation, err)
	default:
		return fmt.Errorf("%w: %s did not complete: %v", ErrInterrupted, operation, err)
	}
}

func snapshotPrivateLedgerNewLock(fd int) error {
	snapshot, err := snapshotPrivateLedgerEntry(fd)
	if err != nil {
		return err
	}
	if snapshot.Size.Value != 0 {
		return driftedField("new private ledger lock size")
	}
	return nil
}

func snapshotPrivateLedgerLock(fd int) (domain.FilesystemSnapshot, error) {
	snapshot, initialized, err := snapshotPrivateLedgerLockState(fd)
	if err != nil {
		return domain.FilesystemSnapshot{}, err
	}
	if !initialized {
		return domain.FilesystemSnapshot{}, driftedField("private ledger lock initialization")
	}
	return snapshot, nil
}

func snapshotPrivateLedgerLockState(fd int) (domain.FilesystemSnapshot, bool, error) {
	snapshot, err := snapshotPrivateLedgerEntry(fd)
	if err != nil {
		return domain.FilesystemSnapshot{}, false, err
	}
	if snapshot.Size.Value == 0 {
		return snapshot, false, nil
	}
	if snapshot.Size.Value != uint64(len(privateLedgerLockContents)) {
		return domain.FilesystemSnapshot{}, false, driftedField("private ledger lock size")
	}
	return snapshot, true, nil
}

func verifyPrivateLedgerLock(ctx context.Context, directoryFD int, expected domain.FilesystemSnapshot) error {
	return verifyPublishedName(ctx, directoryFD, privateLedgerLockBasename, expected, []byte(privateLedgerLockContents))
}

func snapshotPrivateLedgerEntry(fd int) (domain.FilesystemSnapshot, error) {
	snapshot, err := SnapshotFD(fd, privateLedgerEntryMask)
	if err != nil {
		return domain.FilesystemSnapshot{}, err
	}
	if snapshot.Type != domain.FileTypeRegular {
		return domain.FilesystemSnapshot{}, driftedField("private ledger entry type")
	}
	if snapshot.UID.Value != uint32(unix.Geteuid()) {
		return domain.FilesystemSnapshot{}, driftedField("private ledger entry owner")
	}
	if snapshot.Mode.Value&0o7777 != durableFileMode {
		return domain.FilesystemSnapshot{}, driftedField("private ledger entry mode")
	}
	if snapshot.LinkCount.Value != 1 {
		return domain.FilesystemSnapshot{}, driftedField("private ledger entry link count")
	}
	if snapshot.Size.Value > maximumDurableFileBytes {
		return domain.FilesystemSnapshot{}, fmt.Errorf("%w: private ledger entry exceeds %d-byte limit", ErrUnsupported, maximumDurableFileBytes)
	}
	return snapshot, nil
}

func readPrivateLedgerRecord(ctx context.Context, directoryFD int, id PrivateLedgerRecordID, maximumBytes int) ([]byte, error) {
	fd, err := openPublishedRecordBeneath(ctx, directoryFD, id.basename())
	if err != nil {
		return nil, err
	}
	defer unix.Close(fd)

	before, err := snapshotPrivateLedgerEntry(fd)
	if err != nil {
		return nil, err
	}
	if before.Size.Value > uint64(maximumBytes) {
		return nil, fmt.Errorf("%w: private ledger record exceeds requested %d-byte read bound", ErrUnsupported, maximumBytes)
	}
	contents := make([]byte, int(before.Size.Value))
	for offset := 0; offset < len(contents); {
		if err := contextError(ctx); err != nil {
			return nil, err
		}
		count, err := unix.Read(fd, contents[offset:])
		if count > 0 {
			offset += count
		}
		if err != nil {
			return nil, fmt.Errorf("%w: read private ledger record: %v", ErrDrifted, err)
		}
		if count == 0 {
			return nil, driftedField("private ledger record content length")
		}
	}
	if err := contextError(ctx); err != nil {
		return nil, err
	}
	var trailing [1]byte
	count, err := unix.Read(fd, trailing[:])
	if count > 0 {
		return nil, driftedField("private ledger record content length")
	}
	if err != nil {
		return nil, fmt.Errorf("%w: read private ledger record terminator: %v", ErrDrifted, err)
	}
	after, err := snapshotPrivateLedgerEntry(fd)
	if err != nil {
		return nil, err
	}
	if before != after {
		return nil, driftedField("private ledger record identity")
	}
	return contents, nil
}

func privateLedgerRecordIDsAt(ctx context.Context, directoryFD, limit int) ([]PrivateLedgerRecordID, error) {
	if limit <= 0 || limit > maximumPrivateLedgerRecords {
		return nil, fmt.Errorf("%w: private ledger inventory limit must be between 1 and %d", ErrUnsupported, maximumPrivateLedgerRecords)
	}
	if err := contextError(ctx); err != nil {
		return nil, err
	}
	directoryFDForRead, err := unix.Openat(directoryFD, ".", unix.O_RDONLY|unix.O_DIRECTORY|unix.O_CLOEXEC|unix.O_NOFOLLOW, 0)
	if err != nil {
		return nil, classifyPrivateLedgerLockOpen(err)
	}
	defer unix.Close(directoryFDForRead)

	buffer := make([]byte, privateLedgerDirectoryReadBytes)
	records := make([]PrivateLedgerRecordID, 0, limit)
	entries := 0
	for {
		if err := contextError(ctx); err != nil {
			return nil, err
		}
		count, err := unix.ReadDirent(directoryFDForRead, buffer)
		if count > 0 {
			_, _, names := unix.ParseDirent(buffer[:count], -1, nil)
			for _, name := range names {
				if name == "." || name == ".." {
					continue
				}
				entries++
				if entries > maximumPrivateLedgerDirEntries {
					return nil, fmt.Errorf("%w: private ledger directory exceeds %d-entry scan bound", ErrUnsupported, maximumPrivateLedgerDirEntries)
				}
				if !strings.HasPrefix(name, privateLedgerNamespacePrefix) {
					continue
				}
				if name == privateLedgerLockBasename {
					continue
				}
				if !strings.HasPrefix(name, privateLedgerRecordPrefix) {
					return nil, fmt.Errorf("%w: unsupported private ledger namespace entry %q", ErrUnsupported, name)
				}
				id, err := privateLedgerRecordIDFromBasename(name)
				if err != nil {
					return nil, fmt.Errorf("%w: malformed private ledger record name %q: %v", ErrDrifted, name, err)
				}
				if len(records) >= limit {
					return nil, fmt.Errorf("%w: private ledger record result exceeds requested %d-entry bound", ErrUnsupported, limit)
				}
				if err := validatePrivateLedgerRecordEntry(ctx, directoryFD, id); err != nil {
					return nil, err
				}
				records = append(records, id)
			}
		}
		if err != nil {
			if errors.Is(err, unix.EINTR) {
				continue
			}
			return nil, fmt.Errorf("%w: enumerate private ledger records: %v", ErrDrifted, err)
		}
		if count == 0 {
			break
		}
	}
	sort.Slice(records, func(left, right int) bool {
		return records[left].basename() < records[right].basename()
	})
	return records, nil
}

func privateLedgerRecordIDFromBasename(basename string) (PrivateLedgerRecordID, error) {
	if !strings.HasPrefix(basename, privateLedgerRecordPrefix) || !strings.HasSuffix(basename, privateLedgerRecordSuffix) {
		return PrivateLedgerRecordID{}, fmt.Errorf("not a v1 private ledger record")
	}
	body := strings.TrimSuffix(strings.TrimPrefix(basename, privateLedgerRecordPrefix), privateLedgerRecordSuffix)
	parts := strings.Split(body, "-")
	if len(parts) != 4 || parts[1] != "ldc" {
		return PrivateLedgerRecordID{}, fmt.Errorf("unexpected v1 private ledger record components")
	}
	id, err := NewPrivateLedgerRecordID(parts[0], "ldc-"+parts[2], parsePrivateLedgerOrdinal(parts[3]))
	if err != nil {
		return PrivateLedgerRecordID{}, err
	}
	if id.basename() != basename {
		return PrivateLedgerRecordID{}, fmt.Errorf("noncanonical private ledger record name")
	}
	return id, nil
}

func parsePrivateLedgerOrdinal(value string) uint8 {
	if len(value) != 2 || value[0] < '0' || value[0] > '9' || value[1] < '0' || value[1] > '9' {
		return maximumPrivateLedgerOrdinal + 1
	}
	return uint8((value[0]-'0')*10 + (value[1] - '0'))
}

func validatePrivateLedgerRecordEntry(ctx context.Context, directoryFD int, id PrivateLedgerRecordID) error {
	fd, err := openPublishedRecordBeneath(ctx, directoryFD, id.basename())
	if err != nil {
		return err
	}
	defer unix.Close(fd)
	_, err = snapshotPrivateLedgerEntry(fd)
	return err
}
